name: Build Scan Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          REGISTRY=${{ steps.login-ecr.outputs.registry }}
          IMAGE_URI=${REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

      - name: Build Docker image with Git SHA
        run: |
          docker build -t "${IMAGE_URI}" ./app

      - name: Security scan with Grype
        uses: anchore/scan-action@v7
        with:
          image: ${{ env.IMAGE_URI }}
          fail-build: true
          severity-cutoff: high
          output-format: json
          output-file: grype-results.json

      - name: Upload Grype scan report
        uses: actions/upload-artifact@v4
        with:
          name: grype-security-scan
          path: grype-results.json

      - name: Push Docker image to ECR
        run: |
          docker push "${IMAGE_URI}"

      - name: Job summary
        run: |
          echo "### Application pipeline successful" >> $GITHUB_STEP_SUMMARY
          echo "- Image pushed: \`${IMAGE_URI}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Image tag: \`${IMAGE_TAG}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Grype scan: passed" >> $GITHUB_STEP_SUMMARY